# Generated by Django 4.2.4 on 2023-08-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="relatedTweets",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Paper",
        ),
        migrations.DeleteModel(
            name="Tweet",
        ),
    ]
